@startuml  
skinparam classAttributeIconSize 0

class Persona {
    - nombre: string
    - rut: string
    + Persona(nombre: string, rut: string)
    + mostrar_informacion(): void  
}

class Estudiante {
    - nota: float
    - beca: float
}

class Docente {
    +registar_calificaciones
}

class Asignatura {
    +asignar_docente
    +aprobar_reprobar_estudiantes
}

class Curso {
    +inscribir_estudiante_curso
}

Persona <|-- Estudiante
Persona <|-- Docente