@startuml  
skinparam classAttributeIconSize 0

class Persona {
    - nombre: string
    - apellido_paterno: string
    - apellido_materno: string
    - rut: string
    + obtener_nombre_completo: string   
}

class Estudiante {
    - nota: float
    - beca: float
}

class Docente {
    +registar_calificaciones
}

class Asignatura {
    +asignar_docente
    +aprobar_reprobar_estudiantes
}

class Curso {
    +inscribir_estudiante_curso
}

Persona <|-- Estudiante
Persona <|-- Docente