@startuml  
skinparam classAttributeIconSize 0

class Persona {
    - nombre: string
    - rut: string
    + Persona(nombre: string, rut: string)
    + mostrar_informacion(): void  
}

class Estudiante {
    - porcentaje_beca: float
}   + Estudiante(nombre: string, rut: string, porcentaje_beca: float)
    + mostrar_informacion(): void

class Docente {
    - especialidad: string
    + Docente(nombre: string, rut: string, especialidad: string)
}

class Asignatura {
    + asignar_docente
    + aprobar_reprobar_asignatura
}

class Curso {
    -arancel_base: float
    +calcular_arancel_final(porcentaje_beca: float): float
    +inscribir_estudiante_curso
}

Persona <|-- Estudiante
Persona <|-- Docente